name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI (Backend)"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4    

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.12.0
    
    # - name: Configurar Docker
    #   uses: docker/setup-docker-action@v4

    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/projeto-integrado-1-gc:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag docker-image:$(date +%s)

      # under work
    #- run: docker push ezequiashimself/projeto-integrado-1-gc
