# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (Backend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes-backend:
    name: Testes e Lint (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json

    - name: Instalar dependências
      run: npm ci

    - name: Verifica Código
      run: npm run lint || true

    - name: Executar Testes
      run: npm test
      
    - name: Verificar Build
      run: npm run build || true
