# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    name: Testes e Lint
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Fixado na versao 20
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Verifica Código
      run: npm run lint  # Corretor Ortográfico

    - name: Executar Testes
      run: npm test
      
    - name: Verificar Build
      run: npm run make


      
